Updated file

🧠 PrepBuddy – Your Ultimate Placement Prep Partner
PrepBuddy is a powerful placement preparation platform designed to help students crack aptitude rounds of top tech companies. With 25+ company-specific aptitude questions, competitive rankings, and features like DP upload, it’s your all-in-one practice arena!
👉 [Click here to access PrepBuddy](https://github.com/SurajSG23/PrepBuddy/issues#)
🌟 Features
🎯 Aptitude Tests – Curated question sets modeled on real company patterns.
🧑‍🎓 Leaderboard & Rankings – See where you stand among fellow aspirants.
📸 Profile Picture Upload – Upload/display your DP using Cloudinary.
🔐 Gmail Login – Secure authentication via Firebase.
📈 Performance Insights – Track your total points and attempts.
🏅 Achievement Badges – Unlock badges as you progress and excel. …

Create Updated file

---

Client/src/App.tsx
Client/src/pages/AIPoweredInterviews.tsx
Client/src/pages/AptitudeTraining.tsx
Client/src/pages/HomePage.tsx
Client/src/pages/TechnicalQuestions.tsx

Added three options in "Choose your focus area" And provided navigation to those 3 tabs.
Preview :

Made the "Choose Your Focus Area" section.

---

Client/package-lock.json
Client/package.json
Client/src/components/Custom/Profile.tsx
Client/src/components/ui/dialog.tsx
Client/src/components/ui/input.tsx
Client/src/pages/Profile.tsx

here i have added the dialog ui components for better usage of the dialog box and also changed the Input component al this are build in components
for that you need to install using this command `npm install @radix-ui/react-dialog`

Improve profile UI

---

Client/src/App.tsx
Client/src/components/Custom/HomePage.tsx
Client/src/components/Custom/TechnicalQuestionsPage.tsx

Added technical questions page

---

Client/src/components/Custom/Header.tsx
Client/src/components/Custom/ThemeToggle.tsx
Client/src/index.css

To Add Theme-Toggle!

---

Client/src/App.tsx
Client/src/components/Custom/TechnicalQuestionsPage.tsx
Client/src/components/Custom/TopicPracticePage.tsx

Preview :
[Recording 2025-07-28 195242.zip](https://github.com/user-attachments/files/21471425/Recording.2025-07-28.195242.zip)
Issue id : #55

Added dedicated technical questions practice page for 4 topics

---

readme.md

Hi @SurajSG23 I have added contributions section in your readme file you can check it out

Updated Readme with Contributions section

---

Client/src/components/Custom/Header.tsx

Handled the Outside click states in the Header.tsx so it will auto close the profile dropdown when clicked on outside from profile.
Issue: #69 
output video ref:
https://github.com/user-attachments/assets/4da160ac-b8b1-499b-a4f6-0a4d4d333576

Fixed Profile dropdown autoclose for outside click

---

Client/package-lock.json
Client/src/components/Custom/Notes.tsx

This PR adds a **search bar** to the Notes section to enhance user navigation and usability.  
As the number of available notes increases, manually browsing becomes inefficient.
The search feature enables users to **quickly find notes by filtering titles in real-time**, improving overall experience.
- 🚀 Faster access to relevant notes  
- 🔍 Real-time filtering for better usability  
- 🧱 Foundation for future enhancements (e.g., tag/category-based search)
Closes #66 
---
I am contributing as part of **GirlScript Summer of Code 2025 (GSSoC'25)**.  Please add some labels to it.
This feature was added to improve usability and aligns with the project’s goal of providing a smoother note-browsing experience.
https://github.com/user-attachments/assets/600ba42e-fb46-4de4-8ef5-cf0e359e77ee

added search bar functionality in notes section

---

Client/src/components/Custom/LandingPage.tsx

- Added smooth hover scaling and shadow transitions to feature cards
- Improves interactivity and visual feedback for users
- Cleaned up spacing and layout

Enhanced feature section cards with hover effects(#77)

---

Client/src/components/Custom/TechnicalQuestionsPage.tsx
Client/src/components/Custom/TopicPracticePage.tsx
Client/src/components/Custom/questions.json
Client/vite.config.ts
Server/app.js
Server/config/db.js
Server/models/testModel.js
Server/models/userModel.js
Server/package-lock.json
Server/package.json
Server/routes/registerRouter.js
Server/routes/testRouter.js

Issue id : #61 
It allows users to select from 12 core computer science topics and answer multiple-choice questions fetched from a new API endpoint.
1. Backend API (/api/questions/:topicName)
- Built a new API endpoint in app.js to serve questions for different topics.
- Created a local questions.json file to act as the data source, populating it with 20 questions for each of the 12 subjects.
- Added robust try...catch error handling for reading the JSON file to prevent server crashes.
2. Module System Conversion
-Converted the entire Node.js backend from CommonJS (require/module.exports) to modern ES Modules (import/export) to resolve module compatibility errors. This affected all server, route, model, and config files.
3. Frontend UI & Logic
- Developed the TechnicalQuestionsPage.tsx …

Feature : Created API and implemented technical questions practice feature for all subjects

---

Client/package.json
Client/src/components/Custom/Header.tsx
Client/src/components/Custom/Profile.tsx
Client/src/components/Custom/QODStatsCard.tsx
Client/src/components/Custom/QuestionOfTheDay.tsx

Implemented QOD ( question of the day) feature for daily motivation and pracitse, it will maintain daily streaks as well. 
Issue: #80

Added Question of the day feature

---

Client/src/components/Custom/FavoritesPage.tsx
Client/src/components/Custom/Notes.tsx

This PR introduces a new feature that allows users to **bookmark notes** and view them under the **Favorites → Bookmarked Notes** section.
---
- 📁 A fully functional **Bookmarked Notes** view
- 🎯 Filters and maps data using `notesData` to ensure titles, images, and download links are accurate
- 💾 Uses `localStorage` to persist bookmarked notes across sessions
- 🔥 User-friendly UI cards matching the Notes layout
---
This feature allows users to:
- 📌 Bookmark important study notes
- 📂 Access them easily under **Favorites**
- ⏱️ Save time by avoiding repeated searches for frequently used resources
---
Closes #65 
---
1. Go to the **Notes** tab
2. Click on the **bookmark icon** on any note
3. Navigate to **Favorites → Bookmarked Notes**
4. Confirm that only the bookmarked notes appear with …

 Added bookmark notes feature

---

LEARN.md

📘 **Added LEARN.md - Learning Hub for PrepBuddy**
This PR introduces a comprehensive **LEARN.md** file designed to guide new contributors and learners through the tech stack and project structure.
**It includes:**
* 📌 Project Overview
* 📂 Folder Structure
* 🔧 Tech Stack Explanation
* 📚 Beginner-Friendly Resources
* 💡 Tips for Running and Understanding the Project
* 🌸 GSSoC Participation Notes
* 🙌 Contributors Section
This addition aims to improve the onboarding experience for both GSSoC contributors and other open-source learners.

Add detailed LEARN.md with tech stack, folder structure, and resources

---

Client/public/aptitudeQuestions.json

- Added more questions for each topic of the aptitude quiz page.
- Fixed the Incorrect Answer Logic and Broken Quiz Links.
- Issue id : #109

Resolved the bug in aptitude quiz page

---

Client/src/App.tsx
Client/src/components/Custom/DSASheet.tsx
Client/src/components/Custom/TechnicalQuestionsPage.tsx
Server/package-lock.json

This PR adds a **filtering system** to the DSA Prep Sheet page, enabling users to filter questions based on:
- 📂 **Topic** (e.g., Arrays, Trees, Graphs)
- 🎯 **Difficulty Level** (Easy, Medium, Hard)
The filters are implemented using dropdowns with Tailwind CSS styling that matches the existing dark-themed gradient UI.
- If no filters selected → show all questions.
- If only topic selected → filter by topic.
- If only difficulty selected → filter by difficulty.
- If both selected → apply both filters.
Helps users quickly focus their DSA practice by selecting questions based on their preferred topics and difficulty levels.
https://github.com/user-attachments/assets/83dc3efc-e7eb-47b5-8178-e86239ecc20d
closes #111

Added dsa prep sheet

---

Client/src/components/Custom/ChatAssistant.tsx
Client/src/components/Custom/Header.tsx
Client/src/components/Custom/OnTopBar.tsx
Client/src/components/Custom/Profile.tsx
Client/src/components/Custom/ThemeToggle.tsx
Client/src/index.css

Hey
https://github.com/user-attachments/assets/5d48dee9-72f4-4235-9ad0-1d00314deac8
Can You see the Changes !
resolved issue #122

To Overlapped Component Fixed and Added ThemeToggle on nav

---

Client/package-lock.json
Client/package.json
Client/src/App.tsx
Client/src/components/Custom/JavaScriptSheet.tsx
Client/src/components/Custom/TechnicalQuestionsPage.tsx

This PR introduces a **JavaScript Interview Practice** page with **20+ commonly asked JavaScript interview questions**, complete with explanations, code examples, and an interactive environment to run and test code directly in the browser.
---
- ✅ **20+ JavaScript interview questions** covering:
- **Beginner**: `var`, `let`, `const`, data types, loops, functions, arrays
- **Intermediate**: closures, promises, async/await, `this` keyword, array methods
- **Advanced**: event loop, prototypes, currying, debouncing/throttling, memory leaks
- ✅ **Code examples** for each question with detailed explanations.
- ✅ **Difficulty level filters** to help users focus on Beginner, Intermediate, or Advanced topics.
- ✅ **Expand/Collapse** UI for better readability.
- ✅ **Interactive code editor** using …

Added js practice page

---

Client/src/App.tsx
Client/src/components/Custom/AiInterviewOptionsPage.tsx
Client/src/components/Custom/AptitudePracticePage.tsx
Client/src/components/Custom/Header.tsx
Client/src/components/Custom/Profile.tsx
Client/src/components/Custom/VoiceInterviewPage.tsx
Client/vite-env.d.ts

Implemented voice-driven interview practice using Web Speech API and AI-generated questions with spoken feedback.
✨ Features
Voice Recording: Speech-to-text for user answers
AI Voice: Text-to-speech for questions and feedback
5-Question Format: Structured interview with progress tracking
Smart Feedback: Concise AI analysis after all questions
**Demo Screenshot**
📱 User Flow
Select Voice Practice → AI speaks question → Record answer → Repeat 5x → Get comprehensive feedback
Ready for review! 🚀
closes #37

implemented Voice Based Practice page in the Ai Based Interview

---

Client/src/App.tsx
Client/src/components/Custom/AiInterviewOptionsPage.tsx
Client/src/components/Custom/AptitudePracticePage.tsx
Client/src/components/Custom/Header.tsx
Client/src/components/Custom/JavaScriptSheet.tsx
Client/src/components/Custom/Profile.tsx
Client/src/components/Custom/VideoInterviewPage.tsx
Client/src/components/Custom/VoiceInterviewPage.tsx
Client/vite-env.d.ts

**Simple Architecture:**
Split Layout: Video feed (left) + Question panel (right)
State Management: React hooks for recording status, responses, current question
Error Handling: Fallback questions if AI fails, camera permission alerts
Clean Reset: Start new interview option after completion
**Integration:**
Added `/ai-interview/video` route in `App.tsx`
Updated `AiInterviewOptionsPage` to enable video button
Reused existing AI session and speech recognition patterns
closes #138

Implemented the Video Based practice page and some bug fixes

---

Client/package-lock.json
Client/package.json
Client/src/App.tsx
Client/src/components/Custom/CppPractice.tsx
Client/src/components/Custom/TechnicalQuestionsPage.tsx

closes #134 
https://github.com/user-attachments/assets/aac9c6bb-f99f-4916-89cf-b38df1ef037f

Added cpp practice sheet

---

readme.md

Hi,
I worked on issue #137 and updated the readme of the repository with clear and concise code snippets that can help new contributors or users quickly understand how to use the project.
I did the following changes:
- Formatted all code snippets using proper syntax highlighting.
- Ensured consistency in style across all snippets.
I have also ensured that the important links remain intact and have also looked for any grammatical improvements. 
Any improvement needed is most welcome. Thank you!

Fixed issue #137: Updated readme.md

---

Client/package-lock.json
Client/package.json
Client/src/App.tsx
Client/src/components/Custom/CppPractice.tsx
Client/src/components/Custom/JavaPractice.tsx
Client/src/components/Custom/TechnicalQuestionsPage.tsx

i have added java page and resolved errors in CppPractice.tsx
closes #135 
https://github.com/user-attachments/assets/4470f0fd-bf0d-4540-ab06-aa26d3e17311

Added java page and resolved errors

---

Client/package-lock.json
Client/src/App.tsx
Client/src/components/Custom/TechnicalQuestionsPage.tsx
Client/src/components/Custom/pythonPractice.tsx
package-lock.json
package.json

Added python page

---

Client/src/App.tsx
Client/src/components/Custom/HtmlPractice.tsx
Client/src/components/Custom/TechnicalQuestionsPage.tsx

closes #146 
https://github.com/user-attachments/assets/4caa2bf5-d848-43c3-9962-f2b1d452e915

Added html page

---

Client/index.html
Client/package-lock.json
Client/package.json
Client/src/components/Custom/Footer.tsx
Client/src/main.tsx

Footer design has been improved and all social links have been maintained in the new design.
Issue #181

Improve footer layout and responsiveness

---

Client/src/components/Custom/Footer.tsx

Added Target and rel attributes so that links will open in a new tab

Add target and rel attributes to footer links

---

Client/src/components/Custom/QuizPage.tsx
Client/src/components/Custom/TestPage.tsx
Client/src/components/ui/canvas-reveal-effect.tsx
Client/src/hooks/useQuizTimer.ts

- Refactor QuizPage and TestPage components.
- enhance type safety and remove unused variables.
- Update canvas-reveal-effect for better type handling. 
- Simplify useQuizTimer by removing unnecessary state management.

Fixed deployment issues

---

Client/src/index.css

This PR fixes the abrupt jump when clicking navbar links by adding smooth scrolling.
- Added `scroll-behavior: smooth` to `html` in index.css.
Closes #207 
Attached video showing smooth scrolling working:
https://github.com/user-attachments/assets/a5d71143-cfd0-49e0-8f4c-35b33a3d1bed

Fix: added smooth scrolling for navbar links
